root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ./cmd/server"
entrypoint = ["./tmp/main"]
include_ext = ["go"]
exclude_dir = ["data", "tmp"]
delay = 500
stop_on_error = true
kill_delay = 500

[log]
time = true

[misc]
clean_on_exit = true
